### ISSUE TITLE
What should I pay attention to when configuring esm?

### ISSUE THREAD

**Issue by Riveer01** [wallabyjs/wallaby-std-esm#2]
Hello, 
I use pm2+esm-wallaby to start the project, but the following error occurs: "Parse is not defined".
Parse is a global object in the third-party package ["parse-server".](https://www.npmjs.com/package/parse-server)
```
const brand = await new Parse.Query('Brand').select('brandName').equalTo('objectId', brandId).first();
```
There is no need using import or require for Parse.Query.
 What should I pay attention to when configuring esm-wallaby?
The following is the relevant configuration to start esm-wallaby in pm2:
```
"script": "index.js",
"node_args": "-r esm-wallaby",
```

**Comment by ArtemGovorov** [comment]
@Riveer01 Are you using Wallaby.js or just `esm-wallaby` npm package?

**Comment by Riveer01** [comment]
@ArtemGovorov Just `esm-wallaby` npm package.

**Comment by ArtemGovorov** [comment]
`esm-wallaby` package is not meant to be used outside of our tools (it's a dependency that we use internally). Please use https://github.com/standard-things/esm. As I can see you have already created a similar issue in that repo, hopefully you get some answers there.

**Comment by Riveer01** [comment]
@ArtemGovorov Thank you very much for your reply, does `esm` support optional chaining, I want to use optional chaining in my project.

**Comment by ArtemGovorov** [comment]
@Riveer01 Unfortunately I don't remember, but you may try it yourself, should be easy to check.

**Comment by Riveer01** [comment]
@ArtemGovorov Ok, I'll give it a try.
